### ISSUE TITLE
Order by stars?

### ISSUE THREAD

**Issue by ac360** [donnemartin/awesome-aws#29]
Donne,

You rock.  I hope everything is going super well for you.  Also, in each category, I think you should order these repos by stars.  Top having the most stars.  Or maybe by commits.  Some people are pouring thousands of hours into these projects.  And I know you know what I'm talking about.  You are crushing it right now with > 500 on SAWS :+1:

**Comment by donnemartin** [comment]
Hi Austen, congrats on the awesome work with Serverless (aka JAWS).  The community appreciates the hard work you all are putting in to help push the new and improved paradigm.

I plan on doing some automation on the repo updating in the near future to help keep the [Fiery Meter of AWSome](https://github.com/donnemartin/awesome-aws#the-fiery-meter-of-awsome) rating for each repo fresh.  It would be cool to also help catch awesome repos that are not already on the list.  This work might include automatic ordering for repos in each section other than alphabetically.

**Comment by ac360** [comment]
:+1: Keep up the great work on all fronts :)
