### ISSUE TITLE
Add info on AWS Lumberyard and Gamelift

### ISSUE THREAD

**Issue by donnemartin** [donnemartin/awesome-aws#35]
http://aws.amazon.com/lumberyard/
http://aws.amazon.com/gamelift/
http://aws.amazon.com/gamedev/

**Comment by zeliard** [comment]
https://github.com/zeliard/GameLift

**Comment by donnemartin** [comment]
Added info to Appendix and zeliard/GameLift to the [Watch List](https://github.com/donnemartin/awesome-aws/issues/34)
