### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by askl56** [donnemartin/awesome-aws#43]
Surely this repo should be called `aws-ome` ? :)

**Comment by donnemartin** [comment]
Catchy :)

The current repo name is somewhat 'standard' for all awesome lists: [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

**Comment by askl56** [comment]
Ofc, was meant partly in jest.

**Comment by donnemartin** [comment]
Figured, thanks for the laugh :)
