### ISSUE TITLE
AWS open guide

### ISSUE THREAD

**Issue by Jogai** [donnemartin/awesome-aws#77]
I'm not into AWS, but this looks like a resource for this list: https://github.com/open-guides/og-aws
Maybe someone with more aws skills than me can look into this if its truly awesome.

**Comment by donnemartin** [comment]
@Jogai thanks for the suggestion!  I think it's a quality resource.  Are you interested in a pull request?  I think it could go here:

### General Guides

AWS Guides:

* [Analyzing Big Data](http://docs.aws.amazon.com/gettingstarted/latest/emr/getting-started-emr-overview.html)
    * [Sentiment Analysis](http://docs.aws.amazon.com/gettingstarted/latest/emr/getting-started-emr-sentiment-tutorial.html)
    * [Web Server Log Analysis](http://docs.aws.amazon.com/gettingstarted/latest/emr/getting-started-emr-tutorial.html)
* [Working with the AWS Management Console](http://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/getting-started.html)
* [Deploying a Web App Using Elastic Beanstalk](http://docs.aws.amazon.com/gettingstarted/latest/deploy/overview.html)
* [Hosting a Web App](http://docs.aws.amazon.com/gettingstarted/latest/wah-linux/web-app-hosting-intro.html)
* [Hosting a .NET Web App](http://docs.aws.amazon.com/gettingstarted/latest/wah/web-app-hosting-intro.html)
* [Hosting a Static Website](http://docs.aws.amazon.com/gettingstarted/latest/swh/website-hosting-intro.html)
* [Quick Start Deployment Guides](https://aws.amazon.com/documentation/quickstart/)

Community Guides:

* [Open Guide to AWS](https://github.com/open-guides/og-aws)   <---**Add**

**Comment by Jogai** [comment]
Maybe, you may do it as well.

**Comment by donnemartin** [comment]
Merged https://github.com/donnemartin/awesome-aws/pull/78, thanks!
